"""add_password_hash_constraints

Revision ID: 19ca7165feb6
Revises: c64310f74a7c
Create Date: 2026-06-25 09:33:46.646043

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19ca7165feb6'
down_revision: Union[str, Sequence[str], None] = 'c64310f74a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
               DELETE
               FROM shipment_tag
               WHERE shipment_id IN (SELECT id FROM shipment WHERE seller_id = '4f37e9a2-c956-4f14-89b2-e8cefc845df8');
               """)

    # 2. Delete the next child level (events)
    op.execute("""
               DELETE
               FROM shipment_event
               WHERE shipment_id IN (SELECT id FROM shipment WHERE seller_id = '4f37e9a2-c956-4f14-89b2-e8cefc845df8');
               """)

    # 3. Delete the parent of those children (shipments)
    op.execute("""
               DELETE
               FROM shipment
               WHERE seller_id = '4f37e9a2-c956-4f14-89b2-e8cefc845df8';
               """)

    # 4. Finally, delete the seller
    op.execute("""
               DELETE
               FROM seller
               WHERE id = '4f37e9a2-c956-4f14-89b2-e8cefc845df8';
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_event', 'location',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_seller_id_fkey'), 'shipment', 'seller', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_seller_email'), 'seller', ['email'], unique=True)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_delivery_partner_email'), 'delivery_partner', ['email'], unique=True)
    op.drop_table('servicable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
