"""add_location_table

Revision ID: 4bd28ce3eb25
Revises: 19ca7165feb6
Create Date: 2026-06-25 09:43:38.175079

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd28ce3eb25'
down_revision: Union[str, Sequence[str], None] = '19ca7165feb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('servicable_location',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partner.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'location_id')
    )
    op.drop_index(op.f('ix_delivery_partner_email'), table_name='delivery_partner')
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_seller_email'), table_name='seller')
    op.drop_constraint(op.f('shipment_seller_id_fkey'), 'shipment', type_='foreignkey')
    op.create_foreign_key(None, 'shipment', 'seller', ['seller_id'], ['id'])
    op.alter_column(
        'shipment_event',
        'location',
        type_=sa.Integer(),
        # This tells Postgres how to convert existing data
        postgresql_using="location::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_event', 'location',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_seller_id_fkey'), 'shipment', 'seller', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_seller_email'), 'seller', ['email'], unique=True)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_delivery_partner_email'), 'delivery_partner', ['email'], unique=True)
    op.drop_table('servicable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
