"""add tag

Revision ID: 859b847a087c
Revises: 9f4fbf9af21d
Create Date: 2026-06-24 09:39:18.729112

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from app.database.models import TagName


# revision identifiers, used by Alembic.
revision: str = '859b847a087c'
down_revision: Union[str, Sequence[str], None] = '9f4fbf9af21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("""
                INSERT INTO tag (id, name, instruction)
                VALUES (gen_random_uuid(), 'EXPRESS', 'Handle with priority deliver within 24 hours'),
                       (gen_random_uuid(), 'STANDARD', 'Regular delivery within 3-5 business days'),
                       (gen_random_uuid(), 'FRAGILE', 'Handle with care contains breakable items'),
                       (gen_random_uuid(), 'HEAVY', 'Weight exceeds 20kg use appropriate equipment'),
                       (gen_random_uuid(), 'INTERNATIONAL', 'Package requires customs clearance'),
                       (gen_random_uuid(), 'DOMESTIC', 'For delivery within country borders only'),
                       (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Keep between 2-8°C at all times'),
                       (gen_random_uuid(), 'GIFT', 'Contains gift items handle discreetly'),
                       (gen_random_uuid(), 'RETURN', 'Package is being returned to sender'),
                       (gen_random_uuid(), 'DOCUMENTS', 'Contains important documents keep dry');
                """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
